FROM amazon/aws-glue-libs:glue_libs_4.0.0_image_01

# Install python packages
COPY src/db/delta_spark/requirements.txt .
RUN pip3 install -r requirements.txt

# Install GCS connector
RUN cd $SPARK_HOME/jars; wget https://storage.googleapis.com/hadoop-lib/gcs/gcs-connector-hadoop3-latest.jar

# Set up directories
RUN mkdir /home/glue_user/pse-stocks-etl

# Set working directory
WORKDIR /home/glue_user/pse-stocks-etl

# Set environment variables
ENV DISABLE_SSL=true DATALAKE_FORMATS=delta

ENTRYPOINT ["bash", "-l"]