name: Daily Sync Job

on:
  schedule:
    - cron: '0 22 * * *' # Runs every day at 6 AM (UTC+8)
  workflow_dispatch:


env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_REPOSITORY: ${{ secrets.DOCKERHUB_REPOSITORY }}


jobs:

  sync-postgres:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      env:
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      run: |
        echo $DOCKERHUB_PASSWORD | docker login --username $DOCKERHUB_USERNAME --password-stdin 

    - name: Pull Docker image
      run: |
        source version.env
        echo "IMAGE_VERSION=$IMAGE_VERSION"
        docker pull ${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_REPOSITORY }}:$IMAGE_VERSION

    - name: Run sync job
      env:
        POSTGRES_DB_ENDPOINT: ${{ secrets.PROD_POSTGRES_DB_ENDPOINT }}
        POSTGRES_DB_USERNAME: ${{ secrets.PROD_POSTGRES_DB_USERNAME }}
        POSTGRES_DB_PASSWORD: ${{ secrets.PROD_POSTGRES_DB_PASSWORD }}
        POSTGRES_DB_PORT: ${{ secrets.PROD_POSTGRES_DB_PORT }}
        POSTGRES_DB_NAME: ${{ secrets.PROD_POSTGRES_DB_NAME }}
      run: |
        source version.env
        echo "IMAGE_VERSION=$IMAGE_VERSION"
        docker run \
          -e POSTGRES_DB_ENDPOINT=$POSTGRES_DB_ENDPOINT \
          -e POSTGRES_DB_USERNAME=$POSTGRES_DB_USERNAME \
          -e POSTGRES_DB_PASSWORD=$POSTGRES_DB_PASSWORD \
          -e POSTGRES_DB_PORT=$POSTGRES_DB_PORT \
          -e POSTGRES_DB_NAME=$POSTGRES_DB_NAME \
          ${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_REPOSITORY }}:$IMAGE_VERSION \
          python -m src.main \
          --destination postgres \
          --action sync \
          --concurrency=4

  sync-bigquery:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create credentials key file
      env:
        GCP_CREDENTIALS_JSON: '${{ secrets.PROD_GCP_CREDENTIALS_JSON }}'
      run: |
        mkdir credentials 
        printf '%s ' $GCP_CREDENTIALS_JSON >| credentials/keyfile.json;

    - name: Log in to Docker Hub
      env:
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      run: |
        echo $DOCKERHUB_PASSWORD | docker login --username $DOCKERHUB_USERNAME --password-stdin 

    - name: Pull Docker image
      run: |
        source version.env
        echo "IMAGE_VERSION=$IMAGE_VERSION"
        docker pull ${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_REPOSITORY }}:$IMAGE_VERSION

    - name: Run sync job
      env:
        GCP_PROJECT_ID: ${{ secrets.PROD_GCP_PROJECT_ID }}
        GCP_CREDENTIALS_FILE: ${{ secrets.PROD_GCP_CREDENTIALS_FILE }}
        GCS_BUCKET_NAME: ${{ secrets.PROD_GCS_BUCKET_NAME }}
        BIGQUERY_LOCATION: ${{ secrets.PROD_BIGQUERY_LOCATION }}
        BIGQUERY_DATASET_ID: ${{ secrets.PROD_BIGQUERY_DATASET_ID }}
      run: |
        source version.env
        echo "IMAGE_VERSION=$IMAGE_VERSION"
        docker run \
          -e GCP_PROJECT_ID=$GCP_PROJECT_ID \
          -e GCP_CREDENTIALS_FILE=$GCP_CREDENTIALS_FILE \
          -e GCS_BUCKET_NAME=$GCS_BUCKET_NAME \
          -e BIGQUERY_LOCATION=$BIGQUERY_LOCATION \
          -e BIGQUERY_DATASET_ID=$BIGQUERY_DATASET_ID \
          -v $PWD/credentials:/pse-stocks-etl/credentials \
          ${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_REPOSITORY }}:$IMAGE_VERSION \
          python -m src.main \
          --destination bigquery \
          --action sync \
          --concurrency=16

  sync-deltalake:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create credentials key file
      env:
        GCP_CREDENTIALS_JSON: '${{ secrets.PROD_GCP_CREDENTIALS_JSON }}'
      run: |
        mkdir credentials 
        printf '%s ' $GCP_CREDENTIALS_JSON >| credentials/keyfile.json;

    - name: Log in to Docker Hub
      env:
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      run: |
        echo $DOCKERHUB_PASSWORD | docker login --username $DOCKERHUB_USERNAME --password-stdin 

    - name: Pull Docker image
      run: |
        source version.env
        echo "IMAGE_VERSION=$IMAGE_VERSION"
        docker pull ${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_REPOSITORY }}:$IMAGE_VERSION

    - name: Run sync job
      env:
        GCP_PROJECT_ID: ${{ secrets.PROD_GCP_PROJECT_ID }}
        GCP_CREDENTIALS_FILE: ${{ secrets.PROD_GCP_CREDENTIALS_FILE }}
        GCS_BUCKET_NAME: ${{ secrets.PROD_GCS_BUCKET_NAME }}
      run: |
        source version.env
        echo "IMAGE_VERSION=$IMAGE_VERSION"
        docker run \
          -e GCP_PROJECT_ID=$GCP_PROJECT_ID \
          -e GCP_CREDENTIALS_FILE=$GCP_CREDENTIALS_FILE \
          -e GCS_BUCKET_NAME=$GCS_BUCKET_NAME \
          -v $PWD/credentials:/pse-stocks-etl/credentials \
          ${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_REPOSITORY }}:$IMAGE_VERSION \
          python -m src.main \
          --destination deltalake \
          --action sync \
          --concurrency=16

  sync-spark-deltalake:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create credentials key file
      env:
        GCP_CREDENTIALS_JSON: '${{ secrets.PROD_GCP_CREDENTIALS_JSON }}'
      run: |
        mkdir credentials 
        printf '%s ' $GCP_CREDENTIALS_JSON >| credentials/keyfile.json;

    - name: Log in to Docker Hub
      env:
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      run: |
        echo $DOCKERHUB_PASSWORD | docker login --username $DOCKERHUB_USERNAME --password-stdin 

    - name: Pull Docker image
      run: |
        source version.env
        echo "IMAGE_VERSION=$IMAGE_VERSION"
        docker pull ${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_REPOSITORY }}:pyspark-$IMAGE_VERSION

    - name: Run sync job
      env:
        GCP_CREDENTIALS_FILE: ${{ secrets.PROD_GCP_CREDENTIALS_FILE }}
        DELTA_TABLE_PATH_PREFIX: ${{ secrets.PROD_DELTA_TABLE_PATH_PREFIX }}
      run: |
        source version.env
        echo "IMAGE_VERSION=$IMAGE_VERSION"
        docker run \
          -e GCP_CREDENTIALS_FILE=$GCP_CREDENTIALS_FILE \
          -e DELTA_TABLE_PATH_PREFIX=$DELTA_TABLE_PATH_PREFIX \
          -v $PWD/credentials:/home/glue_user/pse-stocks-etl/credentials \
          ${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_REPOSITORY }}:pyspark-$IMAGE_VERSION
