name: Daily Sync Job

on:
  schedule:
    - cron: '0 22 * * *' # Runs every day at 6 AM (UTC+8)
  workflow_dispatch:


env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_REPOSITORY: ${{ secrets.DOCKERHUB_REPOSITORY }}


jobs:

  sync_database:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      env:
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      run: |
        echo $DOCKERHUB_PASSWORD | docker login --username $DOCKERHUB_USERNAME --password-stdin 

    - name: Pull Docker image
      run: |
        source version.env
        echo "IMAGE_VERSION=$IMAGE_VERSION"
        docker pull ${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_REPOSITORY }}:$IMAGE_VERSION

    - name: Build Docker image
      run: docker build . --file Dockerfile --tag pse-stocks-etl
      
    - name: Run sync job
      env:
        POSTGRES_DB_ENDPOINT: ${{ secrets.PROD_POSTGRES_DB_ENDPOINT }}
        POSTGRES_DB_USERNAME: ${{ secrets.PROD_POSTGRES_DB_USERNAME }}
        POSTGRES_DB_PASSWORD: ${{ secrets.PROD_POSTGRES_DB_PASSWORD }}
        POSTGRES_DB_PORT: ${{ secrets.PROD_POSTGRES_DB_PORT }}
        POSTGRES_DB_NAME: ${{ secrets.PROD_POSTGRES_DB_NAME }}
      run: |
        source version.env
        echo "IMAGE_VERSION=$IMAGE_VERSION"
        docker run ${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_REPOSITORY }}:$IMAGE_VERSION \
          -e POSTGRES_DB_ENDPOINT=$POSTGRES_DB_ENDPOINT \
          -e POSTGRES_DB_USERNAME=$POSTGRES_DB_USERNAME \
          -e POSTGRES_DB_PASSWORD=$POSTGRES_DB_PASSWORD \
          -e POSTGRES_DB_PORT=$POSTGRES_DB_PORT \
          -e POSTGRES_DB_NAME=$POSTGRES_DB_NAME \
          ${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_REPOSITORY }}:$IMAGE_VERSION \
          python -m src.etl.sync
          pse-stocks-etl python -m src.main \
          --destination postgres \
          --action sync \
          --concurrency=4
