name: Daily Sync Job

on:
  schedule:
    - cron: '0 22 * * *' # Runs every day at 6 AM (UTC+8)
  workflow_dispatch:

jobs:

  build_and_run:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build . --file Dockerfile --tag pse-stocks-etl
      
    - name: Run sync job
      env:
        DATABASE_ENDPOINT: ${{ secrets.PROD_DATABASE_ENDPOINT }}
        DATABASE_USERNAME: ${{ secrets.PROD_DATABASE_USERNAME }}
        DATABASE_PASSWORD: ${{ secrets.PROD_DATABASE_PASSWORD }}
        DATABASE_PORT: ${{ secrets.PROD_DATABASE_PORT }}
        DATABASE_NAME: ${{ secrets.PROD_DATABASE_NAME }}
      run: |
        docker run --name pse-stocks-etl \
          -e DATABASE_ENDPOINT=$DATABASE_ENDPOINT \
          -e DATABASE_USERNAME=$DATABASE_USERNAME \
          -e DATABASE_PASSWORD=$DATABASE_PASSWORD \
          -e DATABASE_PORT=$DATABASE_PORT \
          -e DATABASE_NAME=$DATABASE_NAME \
          pse-stocks-etl python -m src.etl.sync

