name: ETL Pipeline Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build . --file Dockerfile --tag pse-stocks-etl
      
      
  run-sync:
    
    runs-on: ubuntu-latest
    
    needs: build
    
    steps:
    
    - name: Run sync job
      env:
        DATABASE_ENDPOINT: ${{ secrets.TEST_DATABASE_ENDPOINT }}
        DATABASE_USERNAME: ${{ secrets.TEST_DATABASE_USERNAME }}
        DATABASE_PASSWORD: ${{ secrets.TEST_DATABASE_PASSWORD }}
        DATABASE_PORT: ${{ secrets.TEST_DATABASE_PORT }}
        DATABASE_NAME: ${{ secrets.TEST_DATABASE_NAME }}
      run: |
        docker run --name pse-stocks-etl \
          -e DATABASE_ENDPOINT=$DATABASE_ENDPOINT \
          -e DATABASE_USERNAME=$DATABASE_USERNAME \
          -e DATABASE_PASSWORD=$DATABASE_PASSWORD \
          -e DATABASE_PORT=$DATABASE_PORT \
          -e DATABASE_NAME=$DATABASE_NAME \
          pse-stocks-etl python -m src.etl.sync
