name: Manual Backfill

on:
  workflow_dispatch:

jobs:

  build_and_run:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build . --file Dockerfile --tag pse-stocks-etl
      
    - name: Run sync job
      env:
        DATABASE_ENDPOINT: ${{ secrets.DATABASE_ENDPOINT }}
        DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
        DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
        DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
        DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
      run: |
        docker run --name pse-stocks-etl \
          -e DATABASE_ENDPOINT=$DATABASE_ENDPOINT \
          -e DATABASE_USERNAME=$DATABASE_USERNAME \
          -e DATABASE_PASSWORD=$DATABASE_PASSWORD \
          -e DATABASE_PORT=$DATABASE_PORT \
          -e DATABASE_NAME=$DATABASE_NAME \
          pse-stocks-etl python -m src.etl.backfill
