name: Delta Lake Sync via Spark

on:
  workflow_dispatch:


env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_REPOSITORY: ${{ secrets.DOCKERHUB_REPOSITORY }}


jobs:

  sync-spark-deltalake:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create credentials key file
      env:
        GCP_CREDENTIALS_JSON: '${{ secrets.PROD_GCP_CREDENTIALS_JSON }}'
      run: |
        mkdir credentials 
        printf '%s ' $GCP_CREDENTIALS_JSON >| credentials/keyfile.json;

    - name: Log in to Docker Hub
      env:
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      run: |
        echo $DOCKERHUB_PASSWORD | docker login --username $DOCKERHUB_USERNAME --password-stdin 

    - name: Pull Docker image
      run: |
        source version.env
        echo "IMAGE_VERSION=$IMAGE_VERSION"
        docker pull ${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_REPOSITORY }}:pyspark-$IMAGE_VERSION

    - name: Run sync job
      env:
        GCP_CREDENTIALS_FILE: ${{ secrets.PROD_GCP_CREDENTIALS_FILE }}
        DELTA_TABLE_PATH_PREFIX: ${{ secrets.PROD_DELTA_TABLE_PATH_PREFIX }}
      run: |
        source version.env
        echo "IMAGE_VERSION=$IMAGE_VERSION"
        docker run \
          -e GCP_CREDENTIALS_FILE=$GCP_CREDENTIALS_FILE \
          -e DELTA_TABLE_PATH_PREFIX=$DELTA_TABLE_PATH_PREFIX \
          -v $PWD/credentials:/home/glue_user/pse-stocks-etl/credentials \
          ${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_REPOSITORY }}:pyspark-$IMAGE_VERSION
