name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  integration-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build . --file Dockerfile --tag pse-stocks-etl

    - name: Run tests
      env:
        POSTGRES_DB_ENDPOINT: ${{ secrets.TEST_POSTGRES_DB_ENDPOINT }}
        POSTGRES_DB_USERNAME: ${{ secrets.TEST_POSTGRES_DB_USERNAME }}
        POSTGRES_DB_PASSWORD: ${{ secrets.TEST_POSTGRES_DB_PASSWORD }}
        POSTGRES_DB_PORT: ${{ secrets.TEST_POSTGRES_DB_PORT }}
        POSTGRES_DB_NAME: ${{ secrets.TEST_POSTGRES_DB_NAME }}
      run: |
        docker run --name pse-stocks-etl \
          -e POSTGRES_DB_ENDPOINT=$POSTGRES_DB_ENDPOINT \
          -e POSTGRES_DB_USERNAME=$POSTGRES_DB_USERNAME \
          -e POSTGRES_DB_PASSWORD=$POSTGRES_DB_PASSWORD \
          -e POSTGRES_DB_PORT=$POSTGRES_DB_PORT \
          -e POSTGRES_DB_NAME=$POSTGRES_DB_NAME \
          pse-stocks-etl sh -c "pytest tests/integration"


  e2e-data-refresh-test-run:
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build . --file Dockerfile --tag pse-stocks-etl
          
    - name: Run sync job
      env:
        POSTGRES_DB_ENDPOINT: ${{ secrets.TEST_POSTGRES_DB_ENDPOINT }}
        POSTGRES_DB_USERNAME: ${{ secrets.TEST_POSTGRES_DB_USERNAME }}
        POSTGRES_DB_PASSWORD: ${{ secrets.TEST_POSTGRES_DB_PASSWORD }}
        POSTGRES_DB_PORT: ${{ secrets.TEST_POSTGRES_DB_PORT }}
        POSTGRES_DB_NAME: ${{ secrets.TEST_POSTGRES_DB_NAME }}
      run: |
        docker run --name pse-stocks-etl \
          -e POSTGRES_DB_ENDPOINT=$POSTGRES_DB_ENDPOINT \
          -e POSTGRES_DB_USERNAME=$POSTGRES_DB_USERNAME \
          -e POSTGRES_DB_PASSWORD=$POSTGRES_DB_PASSWORD \
          -e POSTGRES_DB_PORT=$POSTGRES_DB_PORT \
          -e POSTGRES_DB_NAME=$POSTGRES_DB_NAME \
          pse-stocks-etl python -m src.main \
          --destination postgres \
          --action sync \
          --concurrency=4
